<a href="https://colab.research.google.com/github/aman9935/machine-learning-based-projects/blob/main/Prediction_of_weight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Prediction of Weight.

In [ ]:
cd

/root


In [ ]:
cd C:\Users\USER\Desktop

[Errno 2] No such file or directory: 'C:UsersUSERDesktop'
/root


In [ ]:
import pandas as pd 
import numpy as np
import itertools

## The given problem based on Classification.

## 1.     Load Datasets

In [ ]:
data=pd.read_csv("/content/weight-height.csv")


In [ ]:
data.head(11)

Gender     Height      Weight
0    Male  73.847017  241.893563
1    Male  68.781904  162.310473
2    Male  74.110105  212.740856
3    Male  71.730978  220.042470
4    Male  69.881796  206.349801
5    Male  67.253016  152.212156
6    Male  68.785081  183.927889
7    Male  68.348516  167.971111
8    Male  67.018950  175.929440
9    Male  63.456494  156.399676
10   Male  71.195382  186.604926

## 2.      Analyze Data

## data.info():

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


## data.describe():

In [ ]:
data.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989698

## data.isnull().sum():

In [ ]:
data.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

##    3. Convert Gender to Number

## Use Label Encoder

In [ ]:
# Step 3 - Convert Gender to number 
# Using LabelEncoder
X = data.iloc[:, :-1].values
y = data.iloc[:, 2].values
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender =  LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

# Optional - if you want to convert X to float data type
import numpy as np
X = np.vstack(X[:, :]).astype(np.float)

## Replace directly in Data Frame

In [ ]:
 # Replace directly in dataframe
data['Gender'].replace('Female',0, inplace=True)
data['Gender'].replace('Male',1, inplace=True)
X = data.iloc[:, :-1].values
y = data.iloc[:, 2].values

In [ ]:
# 1 represent gender of Male.
# 0 represent gender of Female.
#this array contains only (gender,height).
X


array([[ 1.        , 73.84701702],
       [ 1.        , 68.78190405],
       [ 1.        , 74.11010539],
       ...,
       [ 0.        , 63.86799221],
       [ 0.        , 69.03424313],
       [ 0.        , 61.94424588]])

## 4. Split datasets into training set and test set

In [ ]:
# we will use 80% of the data for training and 20% of the data for testing. 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_train.shape

(8000, 2)

In [ ]:
X_test.shape

(2000, 2)

In [ ]:
y_test.shape

(2000,)

In [ ]:
y_train.shape

(8000,)

## 5. Fit Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## 6. Predict test set values

In [ ]:
# Let's compare the predicted values(lin_pred) with actual values(y_test).
# We can see that our model did a fairly good job.
predictions = lin_reg.predict(X_test)

In [ ]:
predictions

array([141.93828842, 176.55658781, 219.77836196, ..., 149.97129636,
       166.83374902, 138.87940677])

In [ ]:
y_test

## 7. Model Accuracy

In [ ]:
lin_reg.score(X_train,y_train)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
loss=mean_squared_error(y_test,predictions)

In [ ]:
loss

97.87152217990108

## 8. Predict my weight

In [ ]:
my_weight_pred = lin_reg.predict([[0,74]])

In [ ]:
my_weight_pred

array([197.2481918])